version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - rust-net
    environment:
      - POSTGRES_DB=graphqlapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/pg/:/var/lib/postgresql/

networks:
  rust-net:
    driver: bridge
